# Generated by Django 3.2.7 on 2021-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='enlistment_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client_info',
            name='tariff',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
