# Generated by Django 3.2.7 on 2021-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210918_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='birth_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='date_taken',
            field=models.CharField(max_length=255),
        ),
    ]
