# Generated by Django 3.2.7 on 2021-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='status',
            field=models.CharField(default='Not Generated', max_length=255),
        ),
    ]
